name: store_api_rest
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.2.0
  shelf_static: ^1.1.1
  postgres: ^3.5.9


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

scripts:
  dev: watchexec -r -w bin -w lib "dart run bin/server.dart"